export interface Game {
  id: string;
  name: string;
  description: string;
  techStack: string;
  icon: string;
  status: "可玩" | "开发中";
  action: "download" | "link";
  link?: string;
  downloadFile?: string;
  category?: string;
}

export const games: Game[] = [
  {
    id: "snake-game",
    name: "贪吃蛇",
    description: "经典贪吃蛇游戏，支持道具和传送门",
    techStack: "Python + pygame-ce",
    icon: "🐍",
    status: "可玩",
    action: "download",
    downloadFile: "/downloads/SnakeWarp.zip",
    category: "休闲游戏",
  },
  {
    id: "insect-game",
    name: "昆虫记",
    description: "基于法布尔《昆虫记》的科普游戏",
    techStack: "HTML + JavaScript",
    icon: "🦗",
    status: "可玩",
    action: "link",
    link: "/games/insect-game",
    category: "休闲游戏",
  },
  {
    id: "reaction-test",
    name: "反应力测试",
    description: "测试你的反应速度",
    techStack: "HTML + JavaScript",
    icon: "⚡",
    status: "可玩",
    action: "link",
    link: "/games/reaction-test",
    category: "休闲游戏",
  },
  {
    id: "spelling-bee",
    name: "单词拼写挑战",
    description: "根据中文意思拼写英文单词，5000+词库",
    techStack: "HTML + JavaScript",
    icon: "🐝",
    status: "可玩",
    action: "link",
    link: "/games/spelling-bee",
    category: "英语学习",
  },
  {
    id: "word-match",
    name: "单词配对记忆",
    description: "翻开卡片匹配英文和中文，锻炼记忆力",
    techStack: "HTML + JavaScript",
    icon: "🃏",
    status: "可玩",
    action: "link",
    link: "/games/word-match",
    category: "英语学习",
  },
  {
    id: "cloze-test",
    name: "完形填空挑战",
    description: "根据语境选择正确的单词填空",
    techStack: "HTML + JavaScript",
    icon: "📝",
    status: "可玩",
    action: "link",
    link: "/games/cloze-test",
    category: "英语学习",
  },
  {
    id: "word-memory",
    name: "单词速记挑战",
    description: "快速记忆单词后测试记忆力",
    techStack: "HTML + JavaScript",
    icon: "🧠",
    status: "可玩",
    action: "link",
    link: "/games/word-memory",
    category: "英语学习",
  },
  {
    id: "math-quiz",
    name: "速算挑战",
    description: "限时内完成加减乘除计算",
    techStack: "HTML + JavaScript",
    icon: "🧮",
    status: "可玩",
    action: "link",
    link: "/games/math-quiz",
    category: "数学训练",
  },
  {
    id: "number-memory",
    name: "数字记忆",
    description: "记住数字序列并准确输入",
    techStack: "HTML + JavaScript",
    icon: "🔢",
    status: "可玩",
    action: "link",
    link: "/games/number-memory",
    category: "数学训练",
  },
  {
    id: "math-24",
    name: "24点游戏",
    description: "用4个数字通过运算得到24",
    techStack: "HTML + JavaScript",
    icon: "🎯",
    status: "可玩",
    action: "link",
    link: "/games/math-24",
    category: "数学训练",
  },
  {
    id: "typing-test",
    name: "打字速度测试",
    description: "测试打字速度和准确率",
    techStack: "HTML + JavaScript",
    icon: "⌨️",
    status: "可玩",
    action: "link",
    link: "/games/typing-test",
    category: "休闲游戏",
  },
  {
    id: "game-2048",
    name: "2048",
    description: "经典数字合并游戏",
    techStack: "HTML + JavaScript",
    icon: "🎲",
    status: "可玩",
    action: "link",
    link: "/games/game-2048",
    category: "休闲游戏",
  },
  {
    id: "sudoku",
    name: "数独",
    description: "经典数字逻辑游戏",
    techStack: "HTML + JavaScript",
    icon: "🔢",
    status: "可玩",
    action: "link",
    link: "/games/sudoku",
    category: "数学训练",
  },
];

export const gameCategories = ["全部", "英语学习", "数学训练", "休闲游戏"];
