import { Tool } from "@/components/ToolCard";

export const tools: Tool[] = [
  {
    id: "win10-activate",
    name: "Win10 激活工具",
    description: "Windows 10 系统激活工具",
    category: "系统工具",
    status: "stable",
    icon: "💻",
    downloadFile: "/downloads/win10-activate.rar",
  },
  {
    id: "bilibili-downloader",
    name: "B站视频下载器",
    description: "下载B站视频到本地MP4文件",
    category: "影音工具",
    status: "stable",
    icon: "📺",
    downloadFile: "/downloads/BilibiliDownloader.zip",
  },
  {
    id: "bilibili-to-audio",
    name: "B站视频转音频",
    description: "将B站视频转换为MP3/WAV/FLAC音频",
    category: "影音工具",
    status: "stable",
    icon: "🎵",
    downloadFile: "/downloads/BilibiliToAudio.zip",
  },
  {
    id: "json-formatter",
    name: "JSON 格式化",
    description: "格式化、压缩、校验 JSON 数据",
    category: "文本处理",
    status: "stable",
    icon: "📋",
  },
  {
    id: "base64",
    name: "Base64 编解码",
    description: "Base64 编码与解码转换",
    category: "加密校验",
    status: "stable",
    icon: "🔐",
  },
  {
    id: "url-encode",
    name: "URL 编解码",
    description: "URL 编码与解码处理",
    category: "文本处理",
    status: "stable",
    icon: "🔗",
  },
  {
    id: "color-converter",
    name: "颜色转换器",
    description: "HEX、RGB、HSL 颜色互转",
    category: "计算换算",
    status: "stable",
    icon: "🎨",
  },
  {
    id: "timestamp",
    name: "时间戳转换",
    description: "Unix 时间戳与日期互转",
    category: "计算换算",
    status: "stable",
    icon: "⏰",
  },
  {
    id: "hash",
    name: "哈希生成器",
    description: "MD5、SHA1、SHA256 哈希计算",
    category: "加密校验",
    status: "stable",
    icon: "🔒",
  },
  {
    id: "image-compressor",
    name: "图片压缩",
    description: "本地压缩图片，不上传服务器",
    category: "图片媒体",
    status: "beta",
    icon: "🖼️",
  },
  {
    id: "regex-tester",
    name: "正则测试",
    description: "实时测试正则表达式匹配",
    category: "开发辅助",
    status: "stable",
    icon: "🔍",
  },
  {
    id: "uuid-generator",
    name: "UUID 生成器",
    description: "生成随机 UUID v4",
    category: "开发辅助",
    status: "stable",
    icon: "🆔",
  },
  {
    id: "unit-converter",
    name: "单位换算",
    description: "长度、重量、温度等单位换算",
    category: "计算换算",
    status: "stable",
    icon: "📐",
  },
  {
    id: "password-generator",
    name: "密码生成器",
    description: "生成安全随机密码",
    category: "加密校验",
    status: "stable",
    icon: "🔑",
  },
  {
    id: "markdown-preview",
    name: "Markdown 预览",
    description: "实时预览 Markdown 渲染效果",
    category: "文本处理",
    status: "stable",
    icon: "📝",
  },
  {
    id: "qr-code",
    name: "二维码生成器",
    description: "生成自定义二维码",
    category: "图片媒体",
    status: "stable",
    icon: "📱",
  },
  {
    id: "text-diff",
    name: "文本对比",
    description: "对比两段文本的差异",
    category: "文本处理",
    status: "stable",
    icon: "📊",
  },
  {
    id: "json-to-ts",
    name: "JSON 转 TS",
    description: "将 JSON 转换为 TypeScript 类型",
    category: "开发辅助",
    status: "stable",
    icon: "🔄",
  },
  {
    id: "number-base",
    name: "进制转换器",
    description: "二进制、八进制、十进制、十六进制互转",
    category: "计算换算",
    status: "stable",
    icon: "🔢",
  },
  {
    id: "cron-generator",
    name: "Cron 生成器",
    description: "可视化生成 Cron 表达式",
    category: "开发辅助",
    status: "stable",
    icon: "⏱️",
  },
  {
    id: "lorem-generator",
    name: "Lorem 生成器",
    description: "生成 Lorem ipsum 占位文本",
    category: "文本处理",
    status: "stable",
    icon: "📄",
  },
  {
    id: "css-unit",
    name: "CSS 单位转换",
    description: "px/rem/em/vw 等单位互转",
    category: "开发辅助",
    status: "stable",
    icon: "📏",
  },
  {
    id: "color-palette",
    name: "颜色调色板",
    description: "生成配色方案",
    category: "图片媒体",
    status: "stable",
    icon: "🎭",
  },
  {
    id: "json-viewer",
    name: "JSON 可视化",
    description: "树形展示 JSON 结构",
    category: "开发辅助",
    status: "stable",
    icon: "🌳",
  },
  {
    id: "word-counter",
    name: "词频统计",
    description: "统计字数、词频、段落数",
    category: "文本处理",
    status: "stable",
    icon: "📈",
  },
  {
    id: "password-strength",
    name: "密码强度检测",
    description: "检测密码强度和破解时间",
    category: "加密校验",
    status: "stable",
    icon: "🛡️",
  },
];

export const categories = [
  "全部",
  "文本处理",
  "图片媒体",
  "影音工具",
  "加密校验",
  "计算换算",
  "开发辅助",
  "系统工具",
];
